[project]
name = "grice-py-aoc-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aoc-lube[utils]>=1.3.3",
    "ipykernel>=7.1.0",
]
